global:
  scrape_interval: 15s

scrape_configs:
  
  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:80']

  - job_name: 'add_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['add_service:80']

  - job_name: 'buscaid_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['buscaid_service:80']
