apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallengeapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techchallengeapi
  template:
    metadata:
      labels:
        app: techchallengeapi
    spec:
      containers:
      - name: techchallengeapi
        image: santosandre/techchallengeapi:1
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__SqlConnection
          value: "Server=sqlserver,1433;Database=TechChallenge;User Id=sa;Password=tech_Chalenge123!;TrustServerCertificate=True"
   
