apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'techchallengeapi'
        metrics_path: /metrics
        static_configs:
          - targets: ['techchallengeapi:80']
      - job_name: 'techchallengeadd'
        metrics_path: /metrics
        static_configs:
          - targets: ['techchallengeadd:80']
      - job_name: 'techchallengeddd'
        metrics_path: /metrics
        static_configs:
          - targets: ['techchallengeddd:80']
      - job_name: 'techchallengebuscaid'
        metrics_path: /metrics
        static_configs:
          - targets: ['techchallengebuscaid:80']
      - job_name: 'techchallengebuscatodos'
        metrics_path: /metrics
        static_configs:
          - targets: ['techchallengebuscatodos:80']
      - job_name: 'techchallengedelete'
        metrics_path: /metrics
        static_configs:
          - targets: ['techchallengedelete:80']
      - job_name: 'techchallengeupdate'
        metrics_path: /metrics
        static_configs:
          - targets: ['techchallengeupdate:80']
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-config
data:
  ACCEPT_EULA: "Y"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ASPNETCORE_URLS: "http://*:80"
  ASPNETCORE_ENVIRONMENT: "Development"
  RabbitMq__Host: "rabbitmq"
  RabbitMq__Port: "5672"
  RabbitMq__UserName: "guest"
  RabbitMq__Password: "guest"

