apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-credentials
  namespace: default
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJzYW50b3NhbmRyZTk1QGhvdG1haWwuY29tIiwKICAgICAgInBhc3N3b3JkIjogIkppcmF5QDIwMTMiCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson

