apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: "tech_Chalenge123!"
        volumeMounts:
        - name: sql-storage
          mountPath: /var/opt/mssql
      volumes:
      - name: sql-storage
        persistentVolumeClaim:
          claimName: sqls-pvc
