apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallengedelete
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techchallengedelete
  template:
    metadata:
      labels:
        app: techchallengedelete
    spec:
      containers:
      - name: techchallengedelete
        image: santosandre/techchallengedelete:1
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__SqlConnection
          value: "Server=sqlserver,1433;Database=TechChallenge;User Id=sa;Password=tech_Chalenge123!;TrustServerCertificate=True"
  