apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: santosandre/techchallengeprometheus:1
        ports:
        - containerPort: 9090
        persistentVolumeClaim:
          claimName: prometheus-pvc
