apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /absolute/path/to/techchallenge/grafana/data 
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-provisioning-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /absolute/path/to/techchallenge/grafana/provisioning 
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-dashboards-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /absolute/path/to/techchallenge/grafana/dashboards  
    type: Directory
