apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  labels:
    app: grafana
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /Pos/techchallenge/grafana/data
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-provisioning-pv
  labels:
    app: grafana
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path:  /Pos/techchallenge/grafana/provisioning
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-dashboards-pv
  labels:
    app: grafana
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path:  /Pos/techchallenge/grafana/dashboards
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  labels:
    app: prometheus
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /Pos/techchallenge/prometheus
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
  labels:
    app: rabbitmq
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path:  /Pos/techchallenge/rabbitmq/dados
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-pv
  labels:
    app: sqlserver
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path:  /Pos/techchallenge/sqlserver
    type: Directory
