apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
type: Opaque
data:
  GF_SECURITY_ADMIN_USER: YWRtaW4=
  GF_SECURITY_ADMIN_PASSWORD: YWRtaW4=
---
apiVersion: v1
kind: Secret
metadata:
  name: sql-credentials
type: Opaque
data:
  MSSQL_SA_PASSWORD: "dGVjaF9DaGFsZW5nZTEyMyE="
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  ConnectionStrings__SqlConnection: "U2VydmVyPXNxbHNlcnZlcjtEYXRhYmFzZT1UZWNoQ2hhbGxlbmdlO1VzZXIgSWQ9c2E7UGFzc3dvcmQ9dGVjaF9DaGFsZW5nZTEyMyE7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT1UcnVl"
