apiVersion: v1
kind: Service
metadata:
  name: techchallengeapi
  labels:
    app: techchallengeapi
spec:
  selector:
    app: techchallengeapi
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
---
apiVersion: v1
kind: Service
metadata:
  name: techchallengeddd
  labels:
    app: techchallengeddd
spec:
  selector:
    app: techchallengeddd
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30085
---
apiVersion: v1
kind: Service
metadata:
  name: techchallengebuscaid
  labels:
    app: techchallengebuscaid
spec:
  selector:
    app: techchallengebuscaid
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082
---
apiVersion: v1
kind: Service
metadata:
  name: techchallengebuscatodos
  labels:
    app: techchallengebuscatodos
spec:
  selector:
    app: techchallengebuscatodos
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30083
---
apiVersion: v1
kind: Service
metadata:
  name: techchallengedelete
  labels:
    app: techchallengedelete
spec:
  selector:
    app: techchallengedelete
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30010
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30900
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
  - name: management
    protocol: TCP
    port: 15672
    targetPort: 15672
    nodePort: 31672
  - name: messaging
    protocol: TCP
    port: 5672
    targetPort: 5672
    nodePort: 30672
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  labels:
    app: sqlserver
spec:
  selector:
    app: sqlserver
  type: NodePort
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: techchallengeupdate
  labels:
    app: techchallengeupdate
spec:
  selector:
    app: techchallengeupdate
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30084
---
apiVersion: v1
kind: Service
metadata:
  name: techchallengeadd
  labels:
    app: techchallengeadd
spec:
  selector:
    app: techchallengeadd
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30086

