apiVersion: v1
kind: Service
metadata:
  name: techchallengeddd
spec:
  selector:
    app: techchallengeddd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30085
  type: NodePort
