apiVersion: v1
kind: Service
metadata:
  name: techchallengebuscaid
spec:
  selector:
    app: techchallengebuscaid
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082
  type: NodePort
