apiVersion: v1
kind: Service
metadata:
  name: techchallengedelete
spec:
  selector:
    app: techchallengedelete
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
