apiVersion: v1
kind: Service
metadata:
  name: techchallengebuscatodos
spec:
  selector:
    app: techchallengebuscatodos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30083
  type: NodePort
