apiVersion: apps/v1
kind: Deployment
metadata:
  name: techchallengeupdate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techchallengeupdate
  template:
    metadata:
      labels:
        app: techchallengeupdate
    spec:
      containers:
      - name: techchallengeupdate
        image: santosandre/techchallengeupdate:1
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__SqlConnection
          value: "Server=sqlserver,1433;Database=TechChallenge;User Id=sa;Password=tech_Chalenge123!;TrustServerCertificate=True"
