on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore Projects
      run: |
        dotnet restore TechChallenge/TechChallengeApi.csproj
        dotnet restore TechChallengeAdd/TechChallengeAdd.csproj
        dotnet restore TechChallengeBuscaDdd/TechChallengeBuscaDdd.csproj
        dotnet restore TechChallengeBuscaId/TechChallengeBuscaId.csproj
        dotnet restore TechChallengeBuscaTodos/TechChallengeBuscaTodos.csproj
        dotnet restore TechChallengeUpdate/TechChallengeUpdate.csproj
        dotnet restore TechChallengeDelete/TechChallengeDelete.csproj

    - name: Build Projects
      run: |
        dotnet build TechChallenge/TechChallengeApi.csproj --configuration Release
        dotnet build TechChallengeAdd/TechChallengeAdd.csproj --configuration Release
        dotnet build TechChallengeBuscaDdd/TechChallengeBuscaDdd.csproj --configuration Release
        dotnet build TechChallengeBuscaId/TechChallengeBuscaId.csproj --configuration Release
        dotnet build TechChallengeBuscaTodos/TechChallengeBuscaTodos.csproj --configuration Release
        dotnet build TechChallengeUpdate/TechChallengeUpdate.csproj --configuration Release
        dotnet build TechChallengeDelete/TechChallengeDelete.csproj --configuration Release

    - name: Test Projects
      run: |
        dotnet test TechChallengeTest/TechChallengeTest.csproj --configuration Release
