on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-restore:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - TechChallenge/TechChallengeApi.csproj
          - TechChallengeAdd/TechChallengeAdd.csproj
          - TechChallengeBuscaDdd/TechChallengeBuscaDdd.csproj
          - TechChallengeBuscaId/TechChallengeBuscaId.csproj
          - TechChallengeBuscaTodos/TechChallengeBuscaTodos.csproj
          - TechChallengeUpdate/TechChallengeUpdate.csproj
          - TechChallengeDelete/TechChallengeDelete.csproj
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore project
      run: dotnet restore ${{ matrix.project }}

    - name: Build project
      run: dotnet build ${{ matrix.project }} --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: build-and-restore
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Run Tests
      run: dotnet test TechChallengeTest/TechChallengeTest.csproj --configuration Release
